lodash/babel-plugin-lodash

src/lodash-modules.js
=> Resolve lodash module path based on the cwd.

src/index.js, test/fixtures/issue-40/actual.js, test/fixtures/issue-40/expected.js
=> support fp methods as arguments; closes #40

package.json
=> chore(package): update babel-cli to version 6.8.0

package.json
=> chore(package): update lodash to version 4.11.2

package.json
=> chore(package): update lodash-es to version 4.11.2

package.json
=> chore(package): update lodash-es to version 4.12.0

package.json
=> chore(package): update babel-plugin-add-module-exports to version 0.2.1

package.json
=> chore(package): update lodash-es to version 4.13.0

package.json
=> chore(package): update babel-core to version 6.9.1

package.json
=> chore(package): update glob to version 7.0.5

package.json
=> chore(package): update babel-core to version 6.10.4

package.json, src/index.js, test/fixtures/syntax-jsx/.babelrc, test/fixtures/syntax-jsx/actual.js, test/fixtures/syntax-jsx/expected.js
Resolves #87.
Hopefully these are the kind of tests you are looking for.
Thanks!
=> JSX expressions

package.json
=> chore(package): update async to version 2.0.0

package.json
=> chore(package): update babel-cli to version 6.11.4

package.json
=> chore(package): update babel-register to version 6.11.5

package.json
=> chore(package): update lodash-es to version 4.14.0

package.json
=> chore(package): update react-bootstrap to version 0.30.1

package.json
=> chore(package): update babel-core to version 6.13.0

package.json
=> chore(package): update babel-plugin-syntax-jsx to version 6.13.0

package.json
=> chore(package): update ramda to version 0.22.1

package.json
=> chore(package): update async to version 2.1.2

package.json
=> chore(package): update babel-core to version 6.18.0

package.json
=> chore(package): update babel-plugin-syntax-jsx to version 6.18.0

package.json
=> chore(package): update babel-register to version 6.18.0

package.json
=> chore(package): update react-bootstrap to version 0.30.6

package.json
=> chore(package): update babel-plugin-transform-runtime to version 6.15.0
